# version 2

# Use Ubuntu Trusty 14.04 image
dist: trusty
sudo: false

branches:
  only:
    - master

language: ruby

cache:
  - apt

before_install:
  - gem install asciidoctor coderay

script:
  - make

after_success:
  - ./publish
